package org.detector.report;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Infer_Report implements Report {

    private String filePath;
    private List<Violation> violations;

    public Infer_Report(String filePath) {
        this.filePath = filePath;
        this.violations = new ArrayList<>();
    }

    @Override
    public String toString() {
        return this.filePath;
    }

    @Override
    public String getFilePath() {
        return this.filePath;
    }

    @Override
    public void addViolation(Violation newViolation) {
        this.violations.add(newViolation);
    }

    @Override
    public List<Violation> getViolations() {
        return this.violations;
    }

    // srcFilePath: source code (which is detected) path, report file: report generated by infer
    public static Report readSingleResultFile(String srcFilepath, File reportFile) {
        Infer_Report report = new Infer_Report(srcFilepath);
        ObjectMapper mapper = new ObjectMapper();
        try {
            JsonNode rootNode = mapper.readTree(reportFile);
            for (int i = 0; i < rootNode.size(); i++) {
                JsonNode violationNode = rootNode.get(i);
                Infer_Violation infer_violation = new Infer_Violation(violationNode);
                report.addViolation(infer_violation);
            }
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return report;
    }

}
